server:
  port: 8088

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Enable the ReactiveDiscoveryClient.
          lower-case-service-id: true
          predicates:
            - name: Path
              args:
                pattern: "'/services/'+serviceId+'/**'" # Defining a pattern for all requests come to API gateway.
          filters:
            - name: RewritePath
              args:
                # The pattern for API gateway to detect the paths that need to rewrite
                regexp: "'/services/' + serviceId+ '/(?<remaining>.*)'"
                # Pattern after rewrite then routing.
                replacement: "'/${remaining}'"
    loadbalancer:
      ribbon:
        # Disable Ribbon to use  ReactiveLoadBalancerFilter instead so we can use the non-blocking load balancer client.
        enabled: false
  redis:
    port: 6379
    host: localhost

eureka:
  client:
    service-url:
      defautl-zone: http://localhost:8761/eureka/
